import type { Activity } from './domain';

export const DEMO_ACTIVITIES: readonly Activity[] = [
  {
    id: 'futbol-5',
    name: 'Fútbol 5',
    displayCategory: 'Deporte',
    description: 'Fomentar el trabajo en equipo, la coordinación y la actividad física mediante partidos de fútbol en formato reducido.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'futbol-campo',
    name: 'Fútbol Campo',
    displayCategory: 'Deporte',
    description: 'Incentivar la cooperación, estrategia y resistencia física a través del fútbol en cancha completa.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'kickingball',
    name: 'Kickingball',
    displayCategory: 'Deporte',
    description: 'Desarrollar habilidades motrices y el trabajo colaborativo mediante un deporte recreativo.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'ultimate',
    name: 'Ultimate',
    displayCategory: 'Deporte',
    description: 'Estimular la actividad física y el juego limpio mediante la práctica de Ultimate.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'voleybol',
    name: 'Voleybol',
    displayCategory: 'Deporte',
    description: 'Favorecer el trabajo en equipo y la coordinación mediante partidos de voleibol.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'arcillita',
    name: 'Arcillita',
    displayCategory: 'Excursión',
    description: 'Explorar el entorno natural promoviendo el aprendizaje y la observación.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'cascaditas',
    name: 'Cascaditas',
    displayCategory: 'Excursión',
    description: 'Disfrutar de un recorrido natural fomentando la aventura y el cuidado del ambiente.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'periodico',
    name: 'Periódico',
    displayCategory: 'Manualidades',
    description: 'Incentivar la creatividad reutilizando materiales reciclables.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'proyecto',
    name: 'Proyecto',
    displayCategory: 'Manualidades',
    description: 'Elaborar una creación manual fortaleciendo la creatividad y la planificación.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'pulseritas',
    name: 'Pulseritas',
    displayCategory: 'Manualidades',
    description: 'Desarrollar la motricidad fina mediante la elaboración de pulseras.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'tablita',
    name: 'Tablita',
    displayCategory: 'Manualidades',
    description: 'Elaborar una manualidad personalizada fortaleciendo habilidades manuales.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'mundialito',
    name: 'Mundialito Eliminatorias',
    displayCategory: 'Competencia',
    description: 'Fomentar la sana competencia y el compañerismo mediante un torneo deportivo.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'hidroslide',
    name: 'Hidroslide',
    displayCategory: 'Piscina',
    description: 'Disfrutar de actividades acuáticas de forma segura y recreativa.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'piscina',
    name: 'Piscina',
    displayCategory: 'Piscina',
    description: 'Incentivar la recreación acuática fortaleciendo habilidades motrices.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'botes',
    name: 'Botes',
    displayCategory: 'Salida',
    description: 'Vivir una experiencia recreativa fortaleciendo la cooperación y el contacto con la naturaleza.',
    durationBlocks: 2,
    maxGroups: 36,
    active: true,
  },
  {
    id: 'caballos',
    name: 'Caballos',
    displayCategory: 'Salida',
    description: 'Acercar a los participantes al cuidado y respeto por los animales mediante la equitación recreativa.',
    maxGroups: 3,
    active: true,
  },
  {
    id: 'ordeno',
    name: 'Ordeño',
    displayCategory: 'Salida',
    description: 'Conocer el proceso de ordeño promoviendo el aprendizaje vivencial del entorno rural.',
    maxGroups: 36,
    active: true,
  },
  {
    id: 'paseo-bici',
    name: 'Paseo en Bici',
    displayCategory: 'Salida',
    description: 'Promover la actividad física y la exploración del entorno mediante un recorrido en bicicleta.',
    maxGroups: 36,
    active: true,
  },
];
