import { CampActivity } from './models';

export const ACTIVITY_CATALOG: CampActivity[] = [
  {
    id: 'futbol-5',
    name: 'Deporte: Fútbol 5',
    category: 'Deporte',
    description: 'Fomentar el trabajo en equipo, la coordinación y la actividad física mediante partidos de fútbol en formato reducido.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'futbol-campo',
    name: 'Deporte: Fútbol Campo',
    category: 'Deporte',
    description: 'Incentivar la cooperación, estrategia y resistencia física a través del fútbol en cancha completa.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'kickingball',
    name: 'Deporte: Kickingball',
    category: 'Deporte',
    description: 'Desarrollar habilidades motrices y el trabajo colaborativo mediante un deporte recreativo.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'ultimate',
    name: 'Deporte: Ultimate',
    category: 'Deporte',
    description: 'Estimular la actividad física y el juego limpio mediante la práctica de Ultimate.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'voleybol',
    name: 'Deporte: Voleybol',
    category: 'Deporte',
    description: 'Favorecer el trabajo en equipo y la coordinación mediante partidos de voleibol.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'arcillita',
    name: 'Excursión: Arcillita',
    category: 'Excursión',
    description: 'Explorar el entorno natural promoviendo el aprendizaje y la observación.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'cascaditas',
    name: 'Excursión: Cascaditas',
    category: 'Excursión',
    description: 'Disfrutar de un recorrido natural fomentando la aventura y el cuidado del ambiente.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'periodico',
    name: 'Manualidades: Periódico',
    category: 'Manualidades',
    description: 'Incentivar la creatividad reutilizando materiales reciclables.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'proyecto',
    name: 'Manualidades: Proyecto',
    category: 'Manualidades',
    description: 'Elaborar una creación manual fortaleciendo la creatividad y la planificación.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'pulseritas',
    name: 'Manualidades: Pulseritas',
    category: 'Manualidades',
    description: 'Desarrollar la motricidad fina mediante la elaboración de pulseras.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'tablita',
    name: 'Manualidades: Tablita',
    category: 'Manualidades',
    description: 'Elaborar una manualidad personalizada fortaleciendo habilidades manuales.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'mundialito',
    name: 'Mundialito Eliminatorias',
    category: 'Competencia',
    description: 'Fomentar la sana competencia y el compañerismo mediante un torneo deportivo.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'hidroslide',
    name: 'Piscina: Hidroslide',
    category: 'Piscina',
    description: 'Disfrutar de actividades acuáticas de forma segura y recreativa.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'piscina',
    name: 'Piscina: Piscina',
    category: 'Piscina',
    description: 'Incentivar la recreación acuática fortaleciendo habilidades motrices.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'botes',
    name: 'Salida: Botes',
    category: 'Salida',
    description: 'Vivir una experiencia recreativa fortaleciendo la cooperación y el contacto con la naturaleza.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'caballos',
    name: 'Salida: Caballos',
    category: 'Salida',
    description: 'Acercar a los participantes al cuidado y respeto por los animales mediante la equitación recreativa.',
    capacity: 3,
    enabled: true,
  },
  {
    id: 'ordeno',
    name: 'Salida: Ordeño',
    category: 'Salida',
    description: 'Conocer el proceso de ordeño promoviendo el aprendizaje vivencial del entorno rural.',
    capacity: 36,
    enabled: true,
  },
  {
    id: 'paseo-bici',
    name: 'Salida: Paseo en Bici',
    category: 'Salida',
    description: 'Promover la actividad física y la exploración del entorno mediante un recorrido en bicicleta.',
    capacity: 36,
    enabled: true,
  },
];
